name: build-test

on:
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm run ci:build
      - run: npm run ci:lint
      - run: npm run ci:test