# Workflow that updates base branch for all open dependabot pull requests.
# Should be triggerred manually by providing new base branch name.

name: Change base branch for all open dependabot pull requests
on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'New base branch name'
        required: true 
        type: string

jobs:
  check-base-branch-exists:
    name: Check that branch ${{ github.event.inputs.base-branch }} exists
    runs-on: ubuntu-latest
    steps:
      - run: git ls-remote --exit-code --heads ${{ github.repositoryUrl }} ${{ github.event.inputs.base-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  fetch-open-depedabot-pull-requests:
    name: Fetch ids of all open dependabot pull requests
    needs:
      - check-base-branch-exists
    runs-on: ubuntu-latest
    outputs:
      description: List of open dependabot pull requests ids
      ids: ${{ steps.pull-requests-list.outputs.ids }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch all open dependabot pull requests ids
        id: pull-requests-list
        run: echo "::set-output name=ids::$(gh pr list --author 'app/dependabot' --state open --json number --jq 'map(.number)')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  change-pull-requests-base-branch:
    name: Change base branch of pull request #${{ matrix.id }} to ${{ github.event.inputs.base-branch }}
    needs:
      - fetch-open-depedabot-pull-requests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    strategy:
      matrix:
        id: ${{fromJson(needs.fetch-open-depedabot-pull-requests.outputs.ids)}}    
    steps:
      - uses: actions/checkout@v3
      - name: Update pull request base branch
        run: gh pr edit ${{ matrix.id }} --base ${{ github.event.inputs.base-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
