# This is a test workflow

name: Update dependabot PRs base branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Base branch'
        required: true 
        type: string

jobs:
  fetch-open-prs:
    runs-on: ubuntu-latest
    outputs:
      prs: ${{ steps.get-prs-matrix.outputs.prs }}
    steps:
      - uses: actions/checkout@v3
      - name: Get PRs
        id: get-prs-matrix
        run: echo "::set-output name=prs::$(gh pr list --author 'app/dependabot' --state open --json number --jq 'map(.number)')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  change-pr-base-branch:
    needs:
      - fetch-open-prs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: ${{fromJson(needs.fetch-open-prs.outputs.prs)}}    
    steps:
      - run: echo ${{ matrix.id }}
      - uses: actions/checkout@v3
      - name: Update PRs base branch
        run: gh pr edit ${{ matrix.id }} --base ${{ github.event.inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

