# This is a test workflow

name: Update base branch for dependabot open pull requests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Change to base branch'
        required: true 
        type: string

jobs:
  fetch-open-prs:
    runs-on: ubuntu-latest
    outputs:
      prs: ${{ steps.get-prs-matrix.outputs.prs }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch all open dependabot pull-requests
        id: get-prs-matrix
        run: echo "::set-output name=prs::$(gh pr list --author 'app/dependabot' --state open --json number --jq 'map(.number)')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  change-pr-base-branch:
    needs:
      - fetch-open-prs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    strategy:
      matrix:
        id: ${{fromJson(needs.fetch-open-prs.outputs.prs)}}    
    steps:
      - uses: actions/checkout@v3
      - name: Update pull request base branch
        run: gh pr edit ${{ matrix.id }} --base ${{ github.event.inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

