# This is a test workflow

name: Update dependabot PRs base branch
on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'Pull request ID'
        required: true 
        type: string

jobs:
  fetch-open-prs:
    runs-on: ubuntu-latest
    outputs:
      prs: ${{ steps.get-prs-matrix.outputs.prs }}
    steps:
      - uses: actions/checkout@v3
      - name: Get PRs
        id: get-prs-matrix
        run: echo "::set-output name=prs::$( gh pr list --app 'dependabot' --state open --json id --jq 'map(.id)')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dependabot-pr-base:
    needs:
      - fetch-open-prs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{fromJson(needs.fetch-open-prs.outputs.prs)}}    
    steps:
      - run: echo ${{ matrix.package }}
    # steps:
    #   - uses: actions/checkout@v3
    #   - run:  gh pr list --author 'app/dependabot' --state open --json id > dependabot.json
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   - run: cat dependabot.json

